{
  "openapi": "3.0.0",
  "info": {
    "title": "DoctorTesting.v1",
    "version": "1.0",
    "description": ""
  },
  "servers": [
    {
      "url": "https://endpoint.denefits.com/v1",
      "description": "Live whitelabel"
    }
  ],
  "paths": {
    "/file/upload": {
      "post": {
        "summary": "Upload file",
        "operationId": "post-file-upload",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "file_id": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success ": {
                    "value": {
                      "message": "Request executed successfully",
                      "code": "success",
                      "data": {
                        "file_id": "file_1GiyMUGL***********"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Returns file_id which can be used in further API's",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string"
                  },
                  "purpose": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "tags": [
          "File"
        ]
      }
    },
    "/provider/payout/list": {
      "get": {
        "summary": "Provider Payout list",
        "tags": [
          "Providers"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "count": {
                          "type": "number"
                        },
                        "list": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "payout_id": {
                                "type": "string"
                              },
                              "payout_status": {
                                "type": "string"
                              },
                              "payout_amount": {
                                "type": "number"
                              },
                              "date_added": {
                                "type": "string"
                              },
                              "arrival_date": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "Request executed successfully",
                      "code": "success",
                      "data": {
                        "count": 41,
                        "list": [
                          {
                            "payout_id": "po_1GqA6RE34EcXOXDeywdy1UUb",
                            "payout_status": "paid",
                            "payout_amount": 2942.27,
                            "date_added": "2020-06-04T03:50:51.000Z",
                            "arrival_date": "2020-06-06T00:00:00.000Z"
                          },
                          {
                            "payout_id": "po_1GjdCJE34EcXOXDeWkinXYi8",
                            "payout_status": "paid",
                            "payout_amount": 496.4,
                            "date_added": "2020-05-17T03:29:55.000Z",
                            "arrival_date": "2020-05-19T00:00:00.000Z"
                          },
                          {
                            "payout_id": "po_1GdTlwE34EcXOXDesiFS0aTA",
                            "payout_status": "paid",
                            "payout_amount": 1797.39,
                            "date_added": "2020-04-30T04:13:16.000Z",
                            "arrival_date": "2020-05-02T00:00:00.000Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "If provider_id is not provided": {
                    "value": {
                      "message": "\"provider_id\" is required",
                      "code": "parameter_missing"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "If invalid auth token provided": {
                    "value": {
                      "message": "Invalid auth token provided",
                      "code": "authentication_failed"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-provider-payout-list",
        "description": "Get listing of all payouts of this account",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "provider_id",
            "required": true
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "limit",
            "required": true
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "skip",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "start_date"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "end_date"
          }
        ]
      }
    },
    "/provider/payout/detail": {
      "get": {
        "summary": "Provider Payout details",
        "tags": [
          "Providers"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "count": {
                          "type": "number"
                        },
                        "transfers": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "code": {
                                "type": "string"
                              },
                              "type": {
                                "type": "string"
                              },
                              "customer_email": {
                                "type": "string"
                              },
                              "customer_name": {
                                "type": "string"
                              },
                              "payment_type": {
                                "type": "string"
                              },
                              "payment_amount": {
                                "type": "number"
                              },
                              "date_added": {
                                "type": "string"
                              },
                              "contract_status": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "Request executed successfully",
                      "code": "success",
                      "data": {
                        "count": 3,
                        "transfers": [
                          {
                            "id": 17506,
                            "code": "TEPMYLX17506",
                            "type": "contract_payment",
                            "customer_email": "example@domain.com",
                            "customer_name": "Ted Baker",
                            "payment_type": "Partial Payment",
                            "payment_amount": 91.96,
                            "date_added": "2020-06-03T14:12:06.000Z",
                            "contract_status": "Active"
                          },
                          {
                            "id": 17506,
                            "code": "TEPMYLX17506",
                            "type": "contract_payment",
                            "customer_email": "example1@domain.com",
                            "customer_name": "Tom sand",
                            "payment_type": "Recurring Payment",
                            "payment_amount": 91.96,
                            "date_added": "2020-06-03T14:05:06.000Z",
                            "contract_status": "Active"
                          },
                          {
                            "id": 4392,
                            "code": "ARB9K44392",
                            "type": "process_payment",
                            "customer_email": "example2@domain.com",
                            "customer_name": "Sood Him",
                            "payment_type": "Payment Processed",
                            "payment_amount": 979.88,
                            "date_added": "2020-06-03T03:42:37.000Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "If provider id in not provided": {
                    "value": {
                      "message": "\"provider_id\" is required",
                      "code": "parameter_missing"
                    }
                  },
                  "If payout id in not provided": {
                    "value": {
                      "message": "\"payout_id\" is required",
                      "code": "parameter_missing"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "If invalid auth token provided": {
                    "value": {
                      "message": "Invalid auth token provided",
                      "code": "authentication_failed"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-provider-payout-detail",
        "description": "Get details of the payouts by payout ID",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "provider_id",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "payout_id",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "limit"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "skip"
          }
        ]
      }
    },
    "/provider/reports/contract": {
      "get": {
        "summary": "Get provider's contract report",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "list": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "contract_code": {
                                "type": "string"
                              },
                              "contract_status": {
                                "type": "string"
                              },
                              "financed_amount": {
                                "type": "number"
                              },
                              "downpayment_amount": {
                                "type": "number"
                              },
                              "interest_rate": {
                                "type": "number"
                              },
                              "next_recurring_date": {
                                "type": "string"
                              },
                              "number_of_payments": {
                                "type": "number"
                              },
                              "remaining_payments": {
                                "type": "number"
                              },
                              "recurring_amount": {
                                "type": "number"
                              },
                              "customer_address": {
                                "type": "string"
                              },
                              "customer_email": {
                                "type": "string"
                              },
                              "customer_name": {
                                "type": "string"
                              },
                              "customer_mobile": {
                                "type": "string"
                              },
                              "date_added": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "Request executed successfully",
                      "code": "success",
                      "data": {
                        "list": [
                          {
                            "contract_code": "TEP5HTJ12743",
                            "contract_status": "Active",
                            "financed_amount": 850,
                            "downpayment_amount": "0.00",
                            "interest_rate": 20,
                            "next_recurring_date": "2020-01-02",
                            "number_of_payments": 6,
                            "remaining_payments": 6,
                            "recurring_amount": 156.44,
                            "customer_address": "#56 street, Schenectady, New York, 12345",
                            "customer_email": "example@domain.com",
                            "customer_name": "Mark Edison",
                            "customer_mobile": "6878236279",
                            "date_added": "2019-11-28"
                          },
                          {
                            "contract_code": "TEPA3YF12812",
                            "contract_status": "Completed",
                            "financed_amount": 900,
                            "downpayment_amount": "0.00",
                            "interest_rate": 20,
                            "next_recurring_date": "2020-01-15",
                            "number_of_payments": 6,
                            "remaining_payments": 0,
                            "recurring_amount": 0,
                            "customer_address": "#767 street, Schenectady, New York, 12345",
                            "customer_email": "example1@domain.com",
                            "customer_name": "Roy Fane",
                            "customer_mobile": "6878236279",
                            "date_added": "2020-01-08"
                          },
                          {
                            "contract_code": "TEPAMHC12832",
                            "contract_status": "Overdue",
                            "financed_amount": 900,
                            "downpayment_amount": "0.00",
                            "interest_rate": 20,
                            "next_recurring_date": "2019-12-01",
                            "number_of_payments": 6,
                            "remaining_payments": 0,
                            "recurring_amount": 0,
                            "customer_address": "#867 Street, Schenectady, New York, 12345",
                            "customer_email": "example2@domain.com",
                            "customer_name": "Tom baker",
                            "customer_mobile": "6878236279",
                            "date_added": "2020-01-09"
                          },
                          {
                            "contract_code": "TEPTS7L12833",
                            "contract_status": "Completed",
                            "financed_amount": 900,
                            "downpayment_amount": "0.00",
                            "interest_rate": 20,
                            "next_recurring_date": "2019-12-01",
                            "number_of_payments": 6,
                            "remaining_payments": 2,
                            "recurring_amount": 0,
                            "customer_address": "#252 street, Schenectady, New York, 12345",
                            "customer_email": "example3@domain.com",
                            "customer_name": "Ted mosby",
                            "customer_mobile": "6878236279",
                            "date_added": "2020-01-09"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-provider-reports-contract",
        "description": "Get report of all the contracts of this account",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "provider_id",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "start_date"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "end_date"
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "authorization": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "authorization": []
    }
  ]
}