{
  "openapi": "3.0.0",
  "info": {
    "title": "provider-paymentAPIs",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/provider/payment/detail": {
      "get": {
        "summary": "Payment details",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "payment_data": {
                          "type": "object",
                          "properties": {
                            "payment_id": {
                              "type": "number"
                            },
                            "payment_code": {
                              "type": "string"
                            },
                            "provider_id": {
                              "type": "string"
                            },
                            "customer_name": {
                              "type": "string"
                            },
                            "payment_amount": {
                              "type": "number"
                            },
                            "transaction_fee": {
                              "type": "number"
                            },
                            "payment_status": {
                              "type": "string"
                            },
                            "reason": {
                              "type": "string"
                            },
                            "payment_receipt": {
                              "type": "string"
                            },
                            "date_added": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "Request executed successfully",
                      "code": "success",
                      "data": {
                        "payment_data": {
                          "payment_id": 4123,
                          "payment_code": "IDNDRH4***",
                          "provider_id": "pr_084aa5f9bad7a2d72a25d7887e365e0f",
                          "customer_name": "Barney Stinson",
                          "payment_amount": 9000,
                          "transaction_fee": 0,
                          "payment_status": "Successfull",
                          "reason": "Liver treatment",
                          "payment_receipt": "https://denefits.s3.amazonaws.com/payment_receipt/Payment_Rece***********84.pdf",
                          "date_added": "2020-05-26T09:48:11.000Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-payment-detail",
        "description": "It returns the payment detail with payment ID",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "provider_id",
            "required": true
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "payment_id",
            "required": true
          }
        ],
        "tags": [
          "Provider Payment"
        ]
      },
      "parameters": []
    },
    "/provider/payment/list": {
      "get": {
        "summary": "List of Payments of a provider",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "count": {
                          "type": "number"
                        },
                        "payment_list": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "payment_id": {
                                "type": "number"
                              },
                              "payment_code": {
                                "type": "string"
                              },
                              "provider_id": {
                                "type": "string"
                              },
                              "customer_name": {
                                "type": "string"
                              },
                              "payment_amount": {
                                "type": "number"
                              },
                              "transaction_fee": {
                                "type": "number"
                              },
                              "payment_status": {
                                "type": "string"
                              },
                              "reason": {
                                "type": "string"
                              },
                              "payment_receipt": {
                                "type": "string"
                              },
                              "date_added": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "Request executed successfully",
                      "code": "success",
                      "data": {
                        "count": 2,
                        "payment_list": [
                          {
                            "payment_id": 4123,
                            "payment_code": "IDNDRH4***",
                            "provider_id": "pr_084aa5f9bad7a2d72a25d7887e365e0f",
                            "customer_name": "Hannah Baker",
                            "payment_amount": 9000,
                            "transaction_fee": 0,
                            "payment_status": "Successfull",
                            "reason": "Dental treatment",
                            "payment_receipt": "https://denefits.s3.amazonaws.com/payment_receipt/Paymen**********4123.pdf",
                            "date_added": "2020-05-26T09:48:11.000Z"
                          },
                          {
                            "payment_id": 4036,
                            "payment_code": "IDSJNV4***",
                            "provider_id": "pr_084aa5f9bad7a2d72a25d7887e365e0f",
                            "customer_name": "Heart Checkup",
                            "payment_amount": 400,
                            "transaction_fee": 0,
                            "payment_status": "Successfull",
                            "reason": null,
                            "payment_receipt": "https://denefits.s3.amazonaws.com/payment_receipt/Payment_Recei********6.pdf",
                            "date_added": "2020-05-22T07:59:41.000Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-payment-list",
        "description": "It returns the details of the payments processed in the provider's account",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "provider_id",
            "required": true,
            "description": "ID of the provider you need payment details for"
          },
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "limit",
            "description": ""
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "skip",
            "description": ""
          }
        ],
        "tags": [
          "Provider Payment"
        ]
      },
      "parameters": []
    },
    "/provider/payment/pay": {
      "post": {
        "summary": "Process Instant Payment",
        "operationId": "post-provider-payment-pay",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "code": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "code": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "Payment processed successfuly.",
                      "code": "success",
                      "data": {
                        "id": 4318,
                        "code": "IDVYPB4318"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "If invalid provider ID is provided": {
                    "value": {
                      "message": "Invalid provider ID",
                      "code": "request_failed"
                    }
                  },
                  "If mandatory field is missing": {
                    "value": {
                      "message": "\"card_token\" is required",
                      "code": "parameter_missing"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "If auth token is invalid": {
                    "value": {
                      "message": "Invalid auth token provided",
                      "code": "authentication_failed"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "provider_id": {
                    "type": "string"
                  },
                  "card_token": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "number"
                  },
                  "reason": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                },
                "required": [
                  "card_token",
                  "amount",
                  "reason",
                  "name",
                  "provider_id"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "provider_id": "pr_38e9136b576d16a08c1ff1*******",
                    "card_token": "tok_visa",
                    "amount": 100,
                    "reason": "Dental treatment",
                    "name": "Ted Mosby"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "description": "This can be used to process an instant payment for the service.",
        "tags": [
          "Provider Payment"
        ]
      }
    }
  },
  "components": {
    "schemas": {}
  }
}